name: skawa_components
version: 0.1.0

dependencies:
  angular: ^4.0.0
  angular_components: 0.6.0
  quiver: 0.25.0
dev_dependencies:
  sass_builder: 0.2.0+1
  test: 0.12.24+2
  angular_test: 1.0.0
  browser: 0.10.0+2
  angular_utility:
    git: https://github.com/skawa-universe/angular_utility.git
  html_unescape:
dependency_overrides:
  sass:
    git:
      url: https://github.com/sass/dart-sass
      ref: e958477
transformers:
- angular
- angular/transform/reflection_remover:
    $include:
      - test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
